### ISSUE TITLE
Issue with the verso clipboard plugin

### ISSUE THREAD

**Issue by thesourav123** [Tommertom/diyDevApp#1]
Whenever i am building the project, i am getting the below error
Note: Removed the Verso Plugin and then it works
BUILD FAILED

Total time: 5.865 secs
(node:12748) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cmd: Command failed with exit code 1 Error output:
C:\ionic\diydevapp\diyDevApp\platforms\android\src\com\verso\cordova\clipboard\Clipboard.java:60: error: cannot find symbol
                clipBoard.setPrimaryClip(clip);
                                         ^
  symbol:   variable clip
  location: class Clipboard
C:\ionic\diydevapp\diyDevApp\platforms\android\src\com\verso\cordova\clipboard\Clipboard.java:60: error: cannot find symbol
                clipBoard.setPrimaryClip(clip);
                ^
  symbol:   variable clipBoard
  location: class Clipboard
C:\ionic\diydevapp\diyDevApp\platforms\android\src\com\verso\cordova\clipboard\Clipboard.java:62: error: no suitable method found for success(boolean)
                callbackContext.success(true);
                               ^
    method CallbackContext.success(JSONObject) is not applicable
      (argument mismatch; boolean cannot be converted to JSONObject)
    method CallbackContext.success(String) is not applicable
      (argument mismatch; boolean cannot be converted to String)
    method CallbackContext.success(JSONArray) is not applicable
      (argument mismatch; boolean cannot be converted to JSONArray)
    method CallbackContext.success(byte[]) is not applicable
      (argument mismatch; boolean cannot be converted to byte[])
    method CallbackContext.success(int) is not applicable
      (argument mismatch; boolean cannot be converted to int)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
(node:12748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Tommertom** [comment]
U have a repo with example where it fails (ionic app)

Seems like issue triggered in the java so I will try a clean example first (curious about this plugin anyway) and then integrate in diyDevApp

**Comment by thesourav123** [comment]
I copied your repo and tried to build it and it gave the above error for verso clipboard plugin. Maybe, newer versions of cordova and android are not supported.
My Environment
```

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : not installed globally

local packages:

    Cordova Platforms : none
    Ionic Framework   : ionic1 1.3.4

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\sd0003\AppData\Local\Android\sdk

Misc:

    backend : pro
```

**Comment by Tommertom** [comment]
Why are you using the verso plugin actually? 

https://github.com/VersoSolutions/CordovaClipboard

The last commit is  years ago and the plugin I tried works and is actually forked from it and has the last commit a few days ago (I took the one suggested in Ionic Native).

https://github.com/ihadeed/cordova-clipboard

**Comment by Tommertom** [comment]
https://forums.adobe.com/thread/2482993

same issue.

**Comment by Tommertom** [comment]
Uncommented the offending java lines and then exception during runtime occurs..

`04-28 20:06:02.556 11183 11255 E PluginManager: Uncaught exception from plugin
04-28 20:06:02.556 11183 11255 E PluginManager: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.ClipDescription.hasMimeType(java.lang.String)' on a null object reference
04-28 20:06:02.556 11183 11255 E PluginManager:         at com.verso.cordova.clipboard.Clipboard.execute(Clipboard.java:41)
04-28 20:06:02.556 11183 11255 E PluginManager:         at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
04-28 20:06:02.556 11183 11255 E PluginManager:         at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
04-28 20:06:02.556 11183 11255 E PluginManager:         at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
04-28 20:06:02.556 11183 11255 E PluginManager:         at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
04-28 20:06:02.556 11183 11255 E PluginManager:         at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
04-28 20:06:02.556 11183 11255 E PluginManager:         at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
04-28 20:06:02.556 11183 11255 E PluginManager:         at android.os.Handler.dispatchMessage(Handler.java:102)
04-28 20:06:02.556 11183 11255 E PluginManager:         at android.os.Looper.loop(Looper.java:150)
04-28 20:06:02.556 11183 11255 E PluginManager:         at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by Tommertom** [comment]
Removed clipboard from config.xml

Multiple problems reported since latest commit

https://forum.ionicframework.com/t/ionic-native-clipboard-build-failed/129157/8
